batch_size: 32
clip_range: 0.30120897639788613
ent_coef: 0.003309898246296862
gae_lambda: 0.8376142006494488
gamma: 0.9219630131701245
learning_rate: 1.561640628113035e-05
max_grad_norm: 0.5646924090731305
n_epochs: 14
n_steps: 1024
net_arch_type: small
vf_coef: 0.589946560416172
